### ISSUE TITLE
Installation problem: What does“Add this path and evaluate require” mean?

### ISSUE THREAD

**Issue by tengpeng** [mck-/Open-VRP#21]
What does "Add this path and evaluate require:" mean?

I have followed the instruction and the termianl said

> peng@peng-ThinkPad-SL410:~/程序/VRP$ push "/home/peng/程序/VRP/Open-VRP" asdf:_central-registry_
> push: getaddrinfo(/home/peng/程序/VRP/Open-VRP): Name or service not known

**Comment by mck-** [comment]
You have to evaluate it in your CL environment (e.g. SLIME), not in your terminal

**Comment by tengpeng** [comment]
Thanks! I have no knowledge about CL environment. However, I have a VRP
problem to solve recently. Could you please recommend any introduction
articles or any other reference that can help me run the
program successfully? Thanks : )

2012/11/16 Marc Kuo notifications@github.com

**Comment by mck-** [comment]
"Practical Common Lisp" is probably a good place to start. Also Google how to set up an environment including:
- Emacs
- SBCL
- Quicklisp
- SLIME

Good luck!
