### ISSUE TITLE
 (in-package 'open-vrp) problem

### ISSUE THREAD

**Issue by tengpeng** [mck-/Open-VRP#22]
I have installed SBCL and asdf, quicklisp and other libraries.

When I input  (in-package 'open-vrp), it shows warning message as follow. I do not know what's wrong. Where should I check? How to solve it? Thanks

---

 (in-package 'open-vrp)

debugger invoked on a SIMPLE-TYPE-ERROR in thread
# <THREAD "main thread" RUNNING {AB4F921}>:

  'OPEN-VRP cannot be coerced to a string.

Type HELP for debugger help, or (SB-EXT:QUIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [ABORT] Exit debugger, returning to top level.

(STRING 'OPEN-VRP)
0] (solve-prob test-vrp (make-instance 'tabu-search :iterations 10 :animatep T))

; in: LAMBDA (#:G799)
;     (SOLVE-PROB TEST-VRP (MAKE-INSTANCE 'TABU-SEARCH :ITERATIONS 10 :ANIMATEP T))
; 
; caught STYLE-WARNING:
;   undefined function: SOLVE-PROB
; 
; caught WARNING:
;   undefined variable: TEST-VRP
; 
; compilation unit finished
;   Undefined function:
;     SOLVE-PROB
;   Undefined variable:
;     TEST-VRP
;   caught 1 WARNING condition
;   caught 1 STYLE-WARNING condition

debugger invoked on a UNBOUND-VARIABLE in thread
# <THREAD "main thread" RUNNING {AB4F921}>:

  The variable TEST-VRP is unbound.

Type HELP for debugger help, or (SB-EXT:QUIT) to exit from SBCL.

restarts (invokable by number or by possibly-abbreviated name):
  0: [ABORT] Reduce debugger level (to debug level 1).
  1:         Exit debugger, returning to top level.

((LAMBDA (#:G799)) #<unavailable argument>)

**Comment by mck-** [comment]
sorry, try `(in-package :open-vrp)`
